### PR TITLE
Workaround fix for removing BR python2

### PR DESCRIPTION
**Pull request by stratakis**

### CODE REVIEW

**Comment by hroncok** [comment]
How does it work?

**Comment by stratakis** [comment]
Not sure of the exact magic behind it, it seems that these files are supposed to be generated, but they need to exist as well.

Solution taken from https://mail.python.org/pipermail/python-dev/2010-December/106425.html

**Comment by encukou** [comment]
These files are generated using Python – basically, you need to have Python installed to fully compile Python.
For this reason, CPython release tarballs (and even the VCS tree) includes such generated files. But, `make` still re-makes them according to the usual rules, i.e. if they're old enough.

According to the [Fedora packaging guidelines](https://fedoraproject.org/wiki/Packaging:Guidelines#Use_of_pregenerated_code), it would be preferred to BuildRequire `python2` here, and re-build these files. But I don't think it really matters; these are hardly the only files that are regenerated like this.
The compliant thing to do would involve [bootstrapping](https://fedoraproject.org/wiki/Packaging:Guidelines#Bootstrapping), but if we want to go that way, let's do it for current `python3` only.

**Comment by stratakis** [comment]
Also for some reason this happens only at F23 and F24, not at F25 or F26

**Comment by torsava** [comment]
> The compliant thing to do would involve bootstrapping, but if we want to go that way, let's do it for current `python3` only.

`python3` in Fedora is already bootstrapped.

**Pull request closed without merging**
